config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'beers/index'
      post 'beers/create'
      delete 'beers/:id', to: 'beers#destroy'
    end
  end


  root 'beers#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/controllers/api/v1/beers_controller.rb
class Api::V1::BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all.order(brand: :asc)
    render json: @beers
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    if @beer
      render json: @beer
    else
      render json: @beer.errors
    end
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)


    if @beer.save
      render json: @beer
    else
      render json: @beer.errors
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy

    render json: { notice: 'Beer was successfully removed.' }
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_beer
    @beer = Beer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_params
    params.permit(:brand, :style, :country, :quantity)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :null_session
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[ show edit update destroy ]

  # GET /beers or /beers.json
  def index

  end

end

app/helpers/api/v1/beers_helper.rb
module Api::V1::BeersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.erb
<div id="<%= dom_id beer %>">
  <p>
    <strong>Brand:</strong>
    <%= beer.brand %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= beer.style %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= beer.country %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= beer.quantity %>
  </p>

</div>

app/views/beers/_form.html.erb
<%= form_with(model: beer) do |form| %>
  <% if beer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
        <% beer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render "form", beer: @beer %>

<br>

<div>
  <%= link_to "Show this beer", @beer %> |
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Beers</h1>

<div id="beers">
  <% @beers.each do |beer| %>
    <%= render beer %>
    <p>
      <%= link_to "Show this beer", beer %>
    </p>
  <% end %>
</div>

<%= link_to "New beer", new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render "form", beer: @beer %>

<br>

<div>
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beer %>

<div>
  <%= link_to "Edit this beer", edit_beer_path(@beer) %> |
  <%= link_to "Back to beers", beers_path %>

  <%= button_to "Destroy this beer", @beer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsReact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_pack_tag "index" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>